### ISSUE TITLE
Contabilizar acessos ao novo site

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/access-counter#12]
Deve ser possível contabilizar acessos ao novo site.

!!! Descrever aqui os padrões das URLs do novo site e mecanismos para a extração dos dicionários !!!

**Comment by rafaelpezzuto** [comment]
@gustavofonseca, um importante documento de apoio são as [Notas sobre Project COUNTER 5](https://docs.google.com/document/d/1gbH-GC4nmLqNloiwxZ4lNR3aAG0nXcwsXcUbnhXSuCM/edit#heading=h.hznfz7mrp2dh). Segue uma tabela que foi construída tempos atrás (sobre as URLs do novo site):

URI | Descrição
-- | --
new.scielo.br/j/{acrônimo}/a/{pid} | Artigo
? | Artigo em XML
? | Resumo de artigo
new.scielo.br/j/{acrônimo}/a/{pid}/?format=pdf | PDF de artigo
new.scielo.br/j/{acrônimo}/a/{pid}/#ModalArticles | Como citar artigo
new.scielo.br/j/{acrônimo}/ | Periódico
new.scielo.br/journal/{acrônimo}/about/#about | Periódico / Sobre
new.scielo.br/journal/{acrônimo}/about/#editors | Periódico / Editores
new.scielo.br/journal/{acrônimo}/about/#instructions | Periódico / Instruções
new.scielo.br/j/{acrônimo}/i/{ano + volume ou fascículo}/ | Issue (Table of Contents)
new.scielo.br/journal/{acrônimo}/feed/ | Issue (RSS)
new.scielo.br/j/{acrônimo}/grid | Issues de periódico
new.scielo.br/journals/alpha | Periódicos
new.scielo.br/journals/thematic | Periódicos por tópico
new.scielo.br/ | Site
new.scielo.br/about/equipe_scielo | Site / Equipe

**Comment by rafaelpezzuto** [comment]
Duplicate of #14
