### ISSUE TITLE
Adicionar suporte à coleção Preprints

### ISSUE THREAD

**Issue by rafaelpezzuto** [scieloorg/access-counter#23]
O sistema deve ser capaz de calcular acessos, no contexto COUNTER R5 adaptado, para a coleção Preprints. Note que um documento Preprint não está vinculado a um periódico e portanto, pode ser associado a um ISSN genérico, por exemplo. Ainda, até certo ponto, parece não ser possível saber, com apenas os dados constantes nos logs de acesso, o idioma de um documento Preprint. Também não há sentido em saber isso no contexto das métricas COUNTER.

É preciso mapear o que significam ITEM_REQUEST e ITEM_INVESTIGATION no contexto de documentos da coleção Preprints.

**Comment by alexxxmendonca** [comment]
@rafaelpezzuto não há, pois trabalhamos com o conceito de DOIs diferentes para cada tradução. Pelo menos por enquanto a plataforma não administra múltiplos DOIs para um mesmo preprint, portanto nós estamos orientando os autores que possuem traduções a fazerem submissões separadas.

Não há planos a curto prazo mas isso pode vir a mudar no futuro, se a plataforma passar a lidar bem com múltiplos DOIs para um mesmo registro/preprint.

**Comment by rafaelpezzuto** [comment]
Está parcialmente resolvido por meio do PR #28.
Falta criar ou adequar a produção de dicionário de insumos (ano de publicação, idioma suportado) com base em dados do OPAC (ou da base nova de dados normalizados).

**Comment by rafaelpezzuto** [comment]
Boa parte da história já foi resolvida. Só falta mapear a calculadora COUNTER para usar os dados da coleção Preprints que já existem no gerador de dicionários. Em etapas, é preciso fazer:

1. Gerar um novo conjunto de dicionários COUNTER;
2. Alterar o código da calculadora COUNTER para usar os dicionários de data e de idioma que contém a coleção Preprints.

**Comment by rafaelpezzuto** [comment]
Resolvido por #46
